platform :ios, '9.0'
use_frameworks!
#inhibit_all_warnings!

target 'RxEpub_Example' do
  pod 'RxEpub', :path => '../'
  target 'RxEpub_Tests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end
end
