platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'RxEpub_Example' do
  pod 'RxEpub', :path => '../'
#  target 'RxEpub_Tests' do
#    inherit! :search_paths
#    pod 'Quick', '~> 1.2.0'
#    pod 'Nimble', '~> 7.0.2'
#  end
end
